version: '3'

services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx
    volumes:
      - /Users/habouiba/42/inception/srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    hostname: ng
