version: '3'

services:
  nginx:
    build: ./requirements/nginx
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/tools/csr.conf:/etc/nginx/csr.conf
      - wordpress_vol:/var/www/html/habouiba.42.fr
    ports:
      - 80:80
      - 443:443
    hostname: nginx
    init: true
    networks:
      - inception
    depends_on:
      - db
      - wp
  db:
    image: mariadb:latest
    build: ./requirements/mariadb
    volumes:
      - /home/habouiba/data:/var/lib/mysql # set this to /home/habouiba/data
    networks:
      - inception
    hostname: mariadb
    init: true
    env_file:
        - ./.env
  wp:
    image: wordpress:latest
    build: ./requirements/wordpress
    init: true
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html/habouiba.42.fr
    depends_on:
      - db
    env_file:
        - ./.env

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress_vol:
