version: '3'

services:
  nginx:
    image: nginx:latest
    build: ./requirements/nginx
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/tools/csr.conf:/etc/nginx/csr.conf
    ports:
      - 80:80
      - 443:443
    hostname: nginx
